import {chromium} from 'playwright-core';
import {writeFile} from 'node:fs/promises';
const dir='/home/alice/.cache/spaceship-management-sim-119';
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});
const context=await browser.newContext({viewport:{width:1600,height:1100},recordVideo:{dir:dir+'/recording',size:{width:1600,height:1100}}});
const page=await context.newPage(); const errors=[];page.on('pageerror', e=>errors.push(e.stack));
await page.goto('http://127.0.0.1:8119/?seed=17');
const designs=await page.evaluate(()=>window.issue119Demo.designs);
await page.evaluate(d=>localStorage.setItem('spaceship-management-sim.blueprints',JSON.stringify([{name:'Miner',design:d.miner},{name:'Hull ship',design:d.hull}])),designs);
await page.reload();
const start=Date.now(); const scenes=[];
const pause=ms=>page.waitForTimeout(ms);
const snapshot=()=>page.evaluate(()=>window.issue119Demo.snapshot());
function check(cond,msg){if(!cond)throw Error(msg);}
async function caption(number){const text=(await page.locator('.ship-build-queue').innerText()).replaceAll('\nCancel','').trim();const storage=await page.locator('#storage-panel').innerText(); await page.evaluate(({number,text})=>{let e=document.getElementById('demo-caption');if(!e){e=document.createElement('div');e.id='demo-caption';e.style.cssText='position:fixed;bottom:0;left:0;right:0;background:#000d;color:white;padding:12px 20px;font:18px sans-serif;z-index:100';document.body.append(e);}e.textContent=`Criteria ${number} • ${text || 'Builder: count '+document.querySelector('.count-value').textContent+' / Queue'}`;},{number,text});console.log('CAPTION',number,text);}
async function still(name){await pause(300);scenes.push({name,time:(Date.now()-start)/1000}); await page.screenshot({path:dir+'/'+name+'.png'});}
async function setup(stock,shortage=0){await page.evaluate(({stock,shortage})=>window.issue119Demo.setup(stock,shortage),{stock,shortage});await pause(250);await page.mouse.click(740,430);await pause(250);check(await page.locator('#ship-menu').isVisible(),'Builder panel missing');}
async function load(index){await page.locator(`[data-blueprint-load="${index}"]`).click();await pause(150);}
async function count(n){let cur=Number(await page.locator('.count-value').innerText());while(cur!==n){await page.locator(`button[data-count="${cur<n?'+':'-'}"]`).click();cur+=cur<n?1:-1;await pause(120);} }
async function queue(index,n){await load(index);await count(n);await page.locator('button[data-build]').click();await pause(250);}
async function advance(seconds){for(let i=0;i<seconds;i++){await page.evaluate(()=>window.issue119Demo.advance(1));await pause(130);}}
try {
console.log('SCENE 1');await setup({miner:3,hull:0});await load(0);await caption('1');await pause(600);await count(2);await pause(400);await count(3);await pause(400);await count(2);await pause(400);await count(1);await page.locator('button[data-count="-"]').click();check(await page.locator('.count-value').innerText()==='1','count below one');await count(3);await page.locator('button[data-build]').click();await pause(250);check((await snapshot()).stations[0].shipBuilds.length===3,'Queue not three');await caption('1');await still('scene1');await pause(1600);
console.log('SCENE 2');await setup({miner:3,hull:1});await queue(1,1);await queue(0,3);await caption('2, 5');check((await page.locator('.ship-build-queue').innerText()).includes('Miner x3'),'missing x3');await still('scene2');await pause(1500);const before=await snapshot();const timer=before.stations[0].shipBuilds[0].timer;await advance(Math.ceil(timer));const after=await snapshot();check(JSON.stringify(after.ships[0].design)===JSON.stringify(designs.hull),'wrong first completed');check(!after.stations[0].shipBuilds[0].waiting && JSON.stringify(after.stations[0].shipBuilds[0].design)===JSON.stringify(designs.miner),'second did not start');await caption('2, 5');await still('scene2-started');await pause(1400);
console.log('SCENE 3');await setup({miner:1,hull:0},40);await load(0);const inventory=(await snapshot()).stations[0].inventory;await page.locator('button[data-build]').click();await pause(300);check(JSON.stringify((await snapshot()).stations[0].inventory)===JSON.stringify(inventory),'queue charged while waiting');check((await page.locator('.ship-build-queue').innerText()).includes('Waiting: 40 more Metal'),'wrong shortfall');await caption('3, 4');await still('scene3');await pause(1300);await page.evaluate(()=>window.issue119Demo.deliver(40));await page.mouse.click(1250,450);await pause(500);await page.mouse.move(740,550);await pause(700);await page.evaluate(()=>{document.getElementById('demo-caption').textContent='Criteria 3, 4 • '+document.getElementById('info').innerText;});await still('scene3-unloading');const deliverySeconds=Math.ceil((await snapshot()).ships.at(-1).timer);await advance(deliverySeconds);await page.mouse.click(740,430);await pause(300);check(!(await snapshot()).stations[0].shipBuilds[0].waiting,'delivery did not start build');await caption('3, 4');await still('scene3-delivered');await pause(1600);
console.log('SCENE 4');await setup({miner:4,hull:2});await queue(1,1);await queue(0,3);await queue(1,1);await queue(0,1);await caption('6');await still('scene4-before');await pause(1200);await page.locator('[data-cancel-build="1"]').click();await pause(300);check((await snapshot()).stations[0].shipBuilds.length===3,'cancel did not remove whole x3');await caption('6');await still('scene4');await pause(1600);
console.log('SCENE 5');await setup({miner:1,hull:1});await queue(0,1);await queue(1,1);await advance(2);const b=await snapshot();await caption('7');await still('scene5-before');await pause(1600);await page.locator('[data-cancel-build="0"]').click();await pause(300);const a=await snapshot();check(a.stations[0].inventory.Metal===60 && a.stations[0].inventory.Ice===40,'full refund minus next payment incorrect');check(!a.stations[0].shipBuilds[0].waiting,'next build not started');console.log('REFUND',b.stations[0].inventory,a.stations[0].inventory);await caption('7');await still('scene5');await pause(2000);
console.log('SCENE 6');await setup({miner:6,hull:6});for(let i=0;i<12;i++)await queue(i%2,1);check((await snapshot()).stations[0].shipBuilds.length===12,'long queue shortened');await caption('8');await still('scene6');await pause(1400);await page.locator('.ship-build-queue').evaluate(e=>{e.scrollTop=120;});await still('scene6-middle');await pause(1200);await page.locator('.ship-build-queue').evaluate(e=>{e.scrollTop=e.scrollHeight;});await still('scene6-bottom');await pause(1800);check(errors.length===0,'page errors '+errors.join('\n'));
}finally{await writeFile(dir+'/scenes.json',JSON.stringify(scenes,null,2));const video=page.video();await context.close();await browser.close();console.log('VIDEO='+await video.path());}
